# netlify.toml for static HTML/CSS/JS site
[build]
  # No build command needed for static HTML
  publish = "."

# Simple redirects for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  # Only redirect URLs that don't point to existing files
  force = false
